<?php

declare(strict_types=1);

final class formhandler_ConstructorTest extends FormhandlerTestCase
{
    final protected function getFormhandlerType(): string
    {
        return "Formhandler";
    }

    public function testStandardFormname_POST(): void
    {
        $form = new FormHandler();

        static::assertEquals(FH_DEFAULT_FORM_NAME, $form->getFormName());
        static::assertFalse($form->isPosted());

        static::assertEquals(1, $form->getCurrentPage());
        static::assertEquals(1, $form->getLastSubmittedPage());
        static::assertEquals(1, $form->getPage());
        static::assertEquals(FH_DEFAULT_LANGUAGE, $form->getLang());
        static::assertEquals(FH_DEFAULT_LANGUAGE, $form->getLanguage());
        static::assertEmpty($form->getJavascriptCode());
        static::assertTrue($form->isCorrect());
        static::assertFalse($form->isViewMode());

        $aExpected = [
            '<form id="' . FH_DEFAULT_FORM_NAME . '" method="post" action="',
            '<ins><input type="hidden" name="FormHandler_submit" id="FormHandler_submit" value="1" />',
            "</ins><table border='0' cellspacing='0' cellpadding='3' >",
            "<p><span style='font-family:tahoma;font-size:10px;color:#B5B5B5;font-weight:normal;'>This form is generated by </span><a href=\"http://www.formhandler.net\" ><span style=\"font-family:Tahoma;font-size:10px;color:#B5B5B5;\"><strong>FormHandler</strong></span></a></p>",
        ];
        static::assertFormFlushContains($form, $aExpected);
    }

    public function testDeviantFormname_POST(): void
    {
        $form = new FormHandler("DeviantFormName");

        static::assertEquals("DeviantFormName", $form->getFormName());

        static::assertFormFlushContains($form, '<form id="DeviantFormName" method="post" action="');
    }

    public function testStandardFormname_POST_submit(): void
    {
        $_POST['FormHandler_submit'] = "1";

        $form = new FormHandler();

        static::assertTrue($form->isPosted());
        static::assertTrue($form->isCorrect());

        static::assertEquals("", $form->flush(true));
    }

    public function testNoExpose(): void
    {
        define('FH_EXPOSE', false);

        $form = new FormHandler();

        $aExpected = [
            '<form id="' . FH_DEFAULT_FORM_NAME . '" method="post" action="',
            '<ins><input type="hidden" name="FormHandler_submit" id="FormHandler_submit" value="1" />',
            "</ins><table border='0' cellspacing='0' cellpadding='3' >"
        ];

        $html = static::assertFormFlushContains($form, $aExpected);

        static::assertStringNotContainsString("<p><span style='font-family:tahoma;font-size:10px;color:#B5B5B5;font-weight:normal;'>This form is generated by </span><a href=\"http://www.formhandler.net\" ><span style=\"font-family:Tahoma;font-size:10px;color:#B5B5B5;\"><strong>FormHandler</strong></span></a></p>", $html);
    }

    public function testTableWith100(): void
    {
        define('FH_DEFAULT_TABLE_WIDTH', 123);

        $form = new FormHandler();

        static::assertFormFlushContains($form, "</ins><table border='0' cellspacing='0' cellpadding='3' width='123' >");
    }

    public function testTableBorder1(): void
    {
        define('FH_DEFAULT_TABLE_BORDER', 99);

        $form = new FormHandler();

        static::assertFormFlushContains($form, "</ins><table border='99' cellspacing='0' cellpadding='3' >");
    }

    public function testTableCellspacing1(): void
    {
        define('FH_DEFAULT_TABLE_CELLSPACING', 99);

        $form = new FormHandler();

        static::assertFormFlushContains($form, "</ins><table border='0' cellspacing='99' cellpadding='3' >");
    }

    public function testTableCellpadding1(): void
    {
        define('FH_DEFAULT_TABLE_CELLPADDING', 99);

        $form = new FormHandler();

        static::assertFormFlushContains($form, "</ins><table border='0' cellspacing='0' cellpadding='99' >");
    }

    public function testNoField(): void
    {
        $form = new FormHandler();

        static::assertNull($form->getValue("notexist"));

        $this->assertTriggertError('Try to get the value of an unknown field "notexist"!', E_USER_WARNING);
    }

    public function testNoName(): void
    {
        // three different versions
        $form = new FormHandler();
        static::assertEquals(FH_DEFAULT_FORM_NAME, $form->getName());
        $form2 = new FormHandler();
        static::assertEquals(FH_DEFAULT_FORM_NAME . "1", $form2->getName());
        $form3 = new FormHandler();
        static::assertEquals(FH_DEFAULT_FORM_NAME . "2", $form3->getName());
    }

    public function testSetAction(): void
    {
        // three different versions
        $form = new FormHandler(null, "action");

        $a = $this->getPrivateProperty($form, "_action");
        static::assertEquals("action", $a);
    }

    public function testSetActionFromQueryString(): void
    {
        $_SERVER['PHP_SELF'] = "phpself.php";

        // three different versions
        $form = new FormHandler();

        $a = $this->getPrivateProperty($form, "_action");
        static::assertEquals("phpself.php", $a);

        $_SERVER['QUERY_STRING'] = "querystring";
        
        // three different versions
        $form2 = new FormHandler();

        $a = $this->getPrivateProperty($form2, "_action");
        static::assertEquals("phpself.php?querystring", $a);
    }

    public function testSetExtra(): void
    {
        // three different versions
        $form = new FormHandler(null, null, "extra");

        $a = $this->getPrivateProperty($form, "_extra");
        static::assertEquals("extra", $a);
    }
}
