name: php 8.0.x

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: Scarlett
        with:
          php_version: 8.0.26
          php_extensions: gd
          configuration: tests/uts/phpunit.xml
          args: --coverage-text

      - name: Code Coverage Check
        uses: sourcetoad/phpunit-coverage-action@v1
        with:
          clover_report_path: output.xml
          min_coverage_percent: 80
          fail_build_on_under: true
